dica/Models/Investment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NPOI.OpenXmlFormats.Spreadsheet;

namespace dica.Models
{
    [Table("Investments")]
    public class Investment
    {
        [Key]
        public Guid UID { get; set; }

        public string TypeOfInvestment { get; set; }

        public string InvestorName { get; set; }

        public string Citizenship { get; set; }

        public Guid InvestorAddressId { get; set; }

        public string OrganizationName { get; set; }

        public Guid OrganizationAddressId { get; set; }

        public string IncorporationPlace { get; set; }

        public string BusinessType { get; set; }

        public Guid InvestmentPermittedAddressId { get; set; }

        public decimal AmountofForeignCapital { get; set; }

        public int PeriodforForeignCapitalBroughtin { get; set; }

        public string PeriodforForeignCapitalBroughtinType { get; set; }

        public decimal TotalAmountofCapital { get; set; }

        public string CapitalCurrency { get; set; }

        public int ConstructionPeriod { get; set; }

        public string ConstructionPeriodType { get; set; }

        public int ValidityofInvestmentPermit { get; set; }

        public string ValidityofInvestmentPermitPeriodType { get; set; }

        public string FormofInvestment { get; set; }
                
        public string CompanyNameinMyanmar { get; set; }

        public int FinancialYearFrom { get; set; }

        public int FinancialYearTo { get; set; }

        public string PermitNo { get; set; }

        public DateTime PermitDate { get; set; }        

        public string Sector { get; set; }

        public string SectorCategory { get; set; }
        
        public string InvestingCountry { get; set; }

        public string Landowner { get; set; }

        public decimal LandArea { get; set; }

        public string LandAreaUnit { get; set; }

        public int LeaseTerm { get; set; }

        public int ExtendedLeaseTerm { get; set; }

        public string AnnualLeaseFee { get; set; }

        public string AnnualLeaseFeeCurrency { get; set; }

        public int TotalNoofLocalEmployee { get; set; }

        public int TotalNoofForeignEmployee { get; set; }

        public int CorporateSocialResponsibility { get; set; }        

        public string EnvironmentandSocialImpactAssessment { get; set; }

        public string CreatedBy { get; set; }

        public DateTimeOffset CreatedOn { get; set; }

        public string ModifiedBy { get; set; }

        public DateTimeOffset? ModifiedOn { get; set; }

        public decimal? LandUsePremium { get; set; }

        public string LandUsePreminumCurrency { get; set; }

        public string Note { get; set; }

    }
}

dica/Models/InvestmentViewModel.cs
using dica.App_LocalResources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace dica.Models
{
    public class InvestmentViewModel
    {
        [Key]
        public Guid UID { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "TypeOfInvestment")]
        public string TypeOfInvestment { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "InvestorName")]
        public string InvestorName { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "Citizenship")]
        public string Citizenship { get; set; }

        public Address InvestorAddress { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "OrganizationName")]
        public string OrganizationName { get; set; }

        public Address OrganizationAddress { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "IncorporationPlace")]
        public string IncorporationPlace { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "BusinessType")]
        public string BusinessType { get; set; }

        [Required]
        public Address InvestmentPermittedAddress { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "AmountofForeignCapital")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.000}")]
        public decimal AmountofForeignCapital { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "PeriodforForeignCapitalBroughtin")]
        public int PeriodforForeignCapitalBroughtin { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "PeriodforForeignCapitalBroughtinType")]
        public string PeriodforForeignCapitalBroughtinType { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "TotalAmountofCapital")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.000}")]
        public decimal TotalAmountofCapital { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "CapitalCurrency")]
        public string CapitalCurrency { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "ConstructionPeriod")]
        public int ConstructionPeriod { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "ConstructionPeriodType")]
        public string ConstructionPeriodType { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "ValidityofInvestmentPermit")]
        public int ValidityofInvestmentPermit { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "ValidityofInvestmentPermitPeriodType")]
        public string ValidityofInvestmentPermitPeriodType { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "FormofInvestment")]
        public string FormofInvestment { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "CompanyNameinMyanmar")]
        public string CompanyNameinMyanmar { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "FinancialYear")]
        public int FinancialYearFrom { get; set; }

        [Required]
        //[Display(ResourceType = typeof(Resource), Name = "CompanyNameinMyanmar")]
        public int FinancialYearTo { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "PermitNo")]
        public string PermitNo { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(Resource), Name = "PermitDate")]
        public DateTime PermitDate { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "Sector")]
        public string Sector { get; set; }

        [Display(ResourceType = typeof(Resource), Name = "SectorCategory")]
        public string SectorCategory { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "InvestingCountry")]
        public string InvestingCountry { get; set; }

        public List<JointVenturePercentage> JointVenturePercentages { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "Landowner")]
        public string Landowner { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "LandArea")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.000}")]
        public decimal LandArea { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "LandAreaUnit")]
        public string LandAreaUnit { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "LeaseTerm")]
        public int LeaseTerm { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "ExtendedLeaseTerm")]
        public int ExtendedLeaseTerm { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "AnnualLeaseFee")]
        public string AnnualLeaseFee { get; set; }

        public string AnnualLeaseFeeCurrency { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "TotalNoofLocalEmployee")]
        public int TotalNoofLocalEmployee { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "TotalNoofForeignEmployee")]
        public int TotalNoofForeignEmployee { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "CorporateSocialResponsibility")]
        public int CorporateSocialResponsibility { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "EnvironmentandSocialImpactAssessment")]
        public string[] EnvironmentandSocialImpactAssessment { get; set; }
        
        public string EnvironmentandSocialImpactAssessmentSelected { get; set; }

        public List<Tax> Taxes { get; set; }

        public List<CapitalDetail> CapitalDetails { get; set; }

        public string TypeOfInvestmentValue { get; set; }

        public string SectorValue { get; set; }

        public string InvestingCountryValue { get; set; }

      
        [Display(ResourceType = typeof(Resource), Name = "CreatedBy")]
        public string CreatedBy { get; set; }

        
        [DataType(DataType.DateTime)]
        [Display(ResourceType = typeof(Resource), Name = "CreatedOn")]
        public DateTimeOffset CreatedOn { get; set; }

    
        [Display(ResourceType = typeof(Resource), Name = "ModifiedBy")]
        public string ModifiedBy { get; set; }

        [DataType(DataType.DateTime)]
        [Display(ResourceType = typeof(Resource), Name = "ModifiedOn")]
        public DateTimeOffset? ModifiedOn { get; set; }

        public string Note { get; set; }

        public string LandUsePreminumCurrency { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.000}")]
        public decimal? LandUsePremium { get; set; }
    }
}

dica/Controllers/InvestmentController.cs
using dica.Models;
using dica.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;

namespace dica.Controllers
{
    [Authorize]
    public class InvestmentController : BaseController
    {
        //const int RecordsPerPage = 10;
        // GET: Investment
        //public ActionResult Index()
        //{
        //    InvestmentSearchViewModel model = new InvestmentSearchViewModel();
        //    List<InvestmentViewModel> investments = InvestmentRepository.GetInvestments();
        //    var pageIndex = model.Page ?? 1;
        //    model.SearchResults = investments.ToPagedList(pageIndex, RecordsPerPage);
        //    return View(model);
        //}

        public ActionResult Index(InvestmentSearchViewModel model)
        {
            //List<InvestmentViewModel> investments = InvestmentRepository.GetInvestments(model);
            //var pageIndex = model.Page ?? 1;
            model.SearchResults = InvestmentRepository.GetInvestments(model);
            return View(model);
        }

        // GET: Investment/Details/5
        public ActionResult Details(Guid id)
        {
            InvestmentViewModel investment = InvestmentRepository.GetInvestment(id);
            return View(investment);
        }

        // GET: Investment/Create
        public ActionResult Create()
        {
            var investment = new InvestmentViewModel();
            //investment.FinancialYearFrom = DateTime.Now.Year;
            //investment.FinancialYearTo = DateTime.Now.Year;
            investment.PermitDate = DateTime.Now;
            investment.CapitalDetails = new List<CapitalDetail>();
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Cash" });
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Machinery" });
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Land Rental" });
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Utilities & Infrastructure" });
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Building" });
            investment.CapitalDetails.Add(new CapitalDetail { Description = "Raw Material" });

            investment.CapitalDetails = investment.CapitalDetails.OrderBy(cd => cd.Description).ToList();
            return View(investment);
        }

        // POST: Investment/Create
        [HttpPost]
        public ActionResult Create(InvestmentViewModel investment)
        {
            try
            {                
                InvestmentRepository.InsertInvestment(investment, User.Identity.Name);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                //throw ex;
                return View(investment);
            }
        }

        // GET: Investment/Edit/5
        public ActionResult Edit(Guid id)
        {
            var investment = InvestmentRepository.GetInvestment(id);
            if (investment.CapitalDetails == null || investment.CapitalDetails.Count == 0)
            {
                investment.CapitalDetails = new List<CapitalDetail>();
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Cash"});
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Machinery"});
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Land Rental"});
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Utilities & Infrastructure"});
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Building"});
                investment.CapitalDetails.Add(new CapitalDetail {Description = "Raw Material"});
            }
            investment.CapitalDetails = investment.CapitalDetails.OrderBy(cd => cd.Description).ToList();
            return View(investment);
        }

        // POST: Investment/Edit/5
        [HttpPost]
        public ActionResult Edit(InvestmentViewModel investment)
        {
            try
            {
                // TODO: Add update logic here
                InvestmentRepository.UpdateInvestment(investment,User.Identity.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
                return View(investment);
            }
        }

        // GET: Investment/Delete/5
        public ActionResult Delete(Guid id)
        {
            var investment = InvestmentRepository.GetInvestment(id);
            return View(investment);
        }

        // POST: Investment/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, Investment investment)
        {
            try
            {
                // TODO: Add delete logic here
                InvestmentRepository.DeleteInvestment(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult JointVenturePercentageList()
        {
            List<JointVenturePercentage> jointVenturePercentages = new List<JointVenturePercentage>();
            jointVenturePercentages.Add(new JointVenturePercentage {CompanyName = "AA", Country = "MM",Percentage = 10});
            jointVenturePercentages.Add(new JointVenturePercentage { CompanyName = "BB", Country = "MM", Percentage = 90 });
            return PartialView("JointVenturePercentageList", jointVenturePercentages);
        }

        public ActionResult GetCountries()
        {
            var countries = CountryRepository.GetCountries();
            return Json(countries, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCurrencies()
        {
            var currencies = StatusRepository.GetStatusByGroup("Currency");
            return Json(currencies, JsonRequestBehavior.AllowGet);
        }
    }
}

dica/Views/Investment/Index.cshtml
@model dica.Models.InvestmentSearchViewModel
@using dica.Repositories
@using PagedList.Mvc;
@{
ViewBag.Title = "Investment List";
}
<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
@*@using (Html.BeginForm("Index", "Investment", FormMethod.Get, new { @class= "navbar-form navbar-search" }))*@
@*{*@
    <div class="panel panel-default panel-table animated fadeInDown">
        <div class="panel-heading">
            <div class="row">
                <div class="col col-xs-6">
                    <h3 class="panel-title">Investment List</h3>
                </div>
                <div class="col col-xs-6 text-right">
                    
                    <button type="button" class="btn btn-primary btn-create" onclick="location.href='@Url.Action("Create", "Investment")'">
                        <span class="glyphicon glyphicon-plus-sign"></span>
                        <span class="label-icon">Create New</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <nav >
                <div >
                    @using (Html.BeginForm("Index", "Investment", FormMethod.Get, new { @class = "form-inline navbar-form navbar-search" }))
                    {
                        <div class="container">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    @Html.DropDownListFor(model => model.TypeOfInvestment, new SelectList(StatusRepository.GetStatusByGroup("TypeOfInvestment"), "Value", "Name"), "Type of Investment", new { @class = "form-control" })
                                </div>
                                <div class="form-group col-md-3">
                                    @Html.DropDownListFor(model => model.Sector, new SelectList(StatusRepository.GetStatusByGroup("Sector"), "Value", "Name"), "Sector", new { @class = "form-control" })
                                </div>
                                <div class="form-group col-md-3">
                                    @Html.DropDownListFor(model => model.InvestingCountry, new SelectList(CountryRepository.GetCountries(), "ISO", "Name"), "Investing Country", new { @class = "form-control selectpicker", data_show_subtext = "true", data_live_search = "true" })
                                </div>
                                <div class="form-group col-md-3">
                                    @Html.EditorFor(model => model.CompanyNameinMyanmar, new { htmlAttributes = new { @class = "form-control", placeholder = "Company Name" } })
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-3">
                                    @Html.EditorFor(model => model.InvestorName, new { htmlAttributes = new { @class = "form-control", placeholder = "Investor Name" } })

                                </div>
                                <div class="form-group col-md-3">
                                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control", placeholder = "Created By" } })

                                </div>
                                <div class="form-group col-md-1">
                                    <div class="input-group">
                                        <div class='input-group date' id="datetimepickerFinancialYearFrom">
                                            @*@Html.TextBoxFor(model => model.FinancialYearFrom, new { @class = "form-control", style = "width:60px" })*@
                                            @Html.TextBoxFor(model => model.FinancialYearFrom, new { @Value = (Model.FinancialYearFrom > 0 ? Model.FinancialYearFrom.ToString() : string.Empty), @class = "form-control", style = "width:60px" })
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-1">
                                    <div class="input-group">
                                        <div class='input-group date' id="datetimepickerFinancialYearTo">
                                            @*@Html.TextBoxFor(model => model.FinancialYearTo, new { @class = "form-control", style = "width:60px" })*@
                                            @Html.TextBoxFor(model => model.FinancialYearTo, new { @Value = (Model.FinancialYearTo > 0 ? Model.FinancialYearTo.ToString() : string.Empty), @class = "form-control", style = "width:60px" })
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-3">
                                    <button type="submit" class="btn btn-search btn-info">
                                        <span class="glyphicon glyphicon-search"></span>
                                        <span class="label-icon">Search</span>
                                    </button>
                                    <button type="reset" class="btn btn-search btn-info">
                                        <span class="glyphicon glyphicon-refresh"></span>
                                        <span class="label-icon">Reset</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                            </div>
            </nav>
            <table class="table table-striped table-bordered table-list">
                <thead>
                    <tr>
                        <th width="1%">
                            #
                        </th>
                        <th width="25%">
                            @Html.DisplayNameFor(model => model.SearchResults[0].CompanyNameinMyanmar)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].InvestorName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].InvestingCountry)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].Sector)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].InvestmentPermittedAddress.State)
                        </th>                        
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].FormofInvestment)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].TotalAmountofCapital)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SearchResults[0].CreatedBy)
                        </th>
                        <th><em class="fa fa-cog"></em></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var rowNo = Model.SearchResults.PageNumber == 1 ? 1 : 1 + (Model.SearchResults.PageNumber*10) - 10;

                        foreach (var item in Model.SearchResults)
                        {
                            <tr>
                                <td width="1%">
                                    @Html.DisplayFor(model => rowNo)
                                </td>
                                <td width="25%">
                                    @Html.DisplayFor(modelItem => item.CompanyNameinMyanmar)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.InvestorName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.InvestingCountry)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sector)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.InvestmentPermittedAddress.State)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FormofInvestment)
                                </td>
                                <td style="text-align: right" width="8%">
                                    @Html.DisplayFor(modelItem => item.TotalAmountofCapital) (@Html.DisplayFor(modelItem => item.CapitalCurrency))
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedBy)
                                </td>
                              
                                <td align="center"  width="22%">
                                    <div class='btn-group pull-right'>
                                        <a class="btn btn-primary" title="Add Attachment" href="#" onclick="location.href='@Url.Action("Index", "Attachment", new { id = item.UID })'"><em class="fa fa-paperclip"></em></a>
                                        <a class="btn btn-info" title="Investment Details" href="#" onclick="location.href='@Url.Action("Details", "Investment", new { id = item.UID })'"><em class="fa fa-list"></em></a>
                                        <a class="btn btn-default" title="Edit Investment" href="#" onclick="location.href='@Url.Action("Edit", "Investment", new { id = item.UID })'"><em class="fa fa-pencil"></em></a>
                                        <a class="btn btn-danger" title="Delete Investment" href="#" onclick="location.href='@Url.Action("Delete", "Investment", new { id = item.UID })'"><em class="fa fa-trash"></em></a>
                                    </div>
                                </td>
                            </tr>
                            rowNo++;
                        }
                    }
                    
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="text-center">
                    @Html.PagedListPager(Model.SearchResults,
           page => Url.Action("Index", new RouteValueDictionary()
           {
               { "Page", page },
               { "TypeOfInvestment", Model.TypeOfInvestment },
               { "Sector", Model.Sector},
               { "InvestingCountry", Model.InvestingCountry },
               { "CompanyNameinMyanmar", Model.CompanyNameinMyanmar },
               { "InvestorName", Model.InvestorName },
               { "CreatedBy", Model.CreatedBy },
               { "FinancialYearFrom", Model.FinancialYearFrom },
               { "FinancialYearTo", Model.FinancialYearTo }
           }),
         PagedListRenderOptions.ClassicPlusFirstAndLast)
                </div>
                </div>
        </div>
    </div>
@*}*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#datetimepickerFinancialYearFrom').datetimepicker({
                format: "YYYY", // Notice the Extra space at the beginning
                viewMode: "years",
                useCurrent: false
            });

            $('#datetimepickerFinancialYearFrom').on("dp.show", function (e) {
                $(e.target).data("DateTimePicker").viewMode("years");
            });

            $('#datetimepickerFinancialYearTo').datetimepicker({
                format: "YYYY", // Notice the Extra space at the beginning
                viewMode: "years",
                useCurrent: false
            });

            $('#datetimepickerFinancialYearTo').val('');

            $('#datetimepickerFinancialYearTo').on("dp.show", function (e) {
                $(e.target).data("DateTimePicker").viewMode("years");
            });

            $('form').on('reset', function () {
                setTimeout(function () {
                    $('.selectpicker').selectpicker('refresh');
                });
            });
        });
    </script>
}